"""empty message

Revision ID: d64d51cd8885
Revises: 
Create Date: 2019-05-04 09:22:29.742523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd64d51cd8885'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'favorite_colors')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('favorite_colors', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
